# Generated by Django 4.0.2 on 2022-02-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_quatity_saleorderline_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='saleorderline',
            name='sale_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.saleorder'),
        ),
    ]
