# Generated by Django 4.0.2 on 2022-02-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderline',
            name='price_total',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
